name: Build and Test

on:
  push:
    branches: [master]
  pull_request: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: npm
    - name: Install dependencies and build
      run: npm ci
    - name: Run tests
      run: npm test
